import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className={`${inter.className} px-3 bg-[#DAE3D1] dark:bg-[#575F51] text-[#202C39] dark:text-[#F5F5F5]`}>
            <Header />
            {children}
        </body>
      </Providers>
    </html>
  );
}